name: Booq-Document-Factory

on:
  workflow_dispatch:
    inputs:
      payload:
        description: "JSON payload (string)"
        required: true
        type: string

jobs:
  install-dependencies:
    name: Create Custom Documents
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache Poetry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pypoetry
            ~/.cache/pip
            .venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install LibreOffice
        run: |
          sudo apt-get update
          sudo apt-get install -y libreoffice

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install prod dependencies (Poetry)
        run: |
          poetry config virtualenvs.in-project true
          poetry install --only main --no-interaction --no-ansi

      - name: Verify installed packages
        run: |
          echo "Installed packages:"

          pip freeze | sed -n '1,100p'

      - name: Print Received Payload
        run: |
          echo "Last Name: $(echo '${{ github.event.inputs.payload }}' | jq -r '.lastName')"
          echo "First Name: $(echo '${{ github.event.inputs.payload }}' | jq -r '.firstName')"
          echo "Birth Date: $(echo '${{ github.event.inputs.payload }}' | jq -r '.birthDate')"
          echo "PESEL: $(echo '${{ github.event.inputs.payload }}' | jq -r '.pesel')"
          echo "Employer Name: $(echo '${{ github.event.inputs.payload }}' | jq -r '.employerName')"
          echo "User Acronym: $(echo '${{ github.event.inputs.payload }}' | jq -r '.userAcronym')"

      - name: Run
        run: |
          poetry run python -m booq_document_factory.main --payload '${{ github.event.inputs.payload }}'

      - name: Upload generated documents
        uses: actions/upload-artifact@v4
        with:
          name: generated-documents
          path: outputfiles/

      - name: Upload files to Sharepoint
        run: |
            poetry run python src/booq_document_factory/sharepoint.py \
                    --hostname "booqpoznan.sharepoint.com" \
                    --site-path "AplicationDeployment" \
                    --drive-name "Biblioteka dokument√≥w" \
                    --base-folder "Pracownicy" \
                    --acronym "$(echo '${{ github.event.inputs.payload }}' | jq -r '.userAcronym')" \
                    --tenant-id "${{ secrets.TENANT_ID }}" \
                    --client-id "${{ secrets.CLIENT_ID }}" \
                    --client-secret "${{ secrets.CLIENT_SECRET }}" \
                    --dir "outputfiles/"
